### ISSUE TITLE
Take ownership of rlab.co.uk website

### ISSUE THREAD

**Issue by JamesBelchamber** [reading-hackspace/Infrastructure#1]
This will track the process of the IWG taking ownership of the rLab website. It is expected that discussion will happen and stories will be created before this can be accepted as done. Details:
- rLab Website
  - Wordpress
  - LAMP

**Comment by JamesBelchamber** [comment]
- Document Wordpress setup in Ansible
- Migrate users to new Wordpress setup

**Comment by JamesBelchamber** [comment]
We need to preserve hyperlinks when migrating anywhere, because there are links on things like hackaday to keep working.

**Comment by Gavatastic** [comment]
There is also some content that relies on widgets/Wp plug-ins. At moment I think:
- two twitter feeds (I think these are embedded html)
- a rotating 'Thanks to:' gallery slideshow on the front page 
- I think some of the video (particularly vimeo i think) is embedded with a video plug-in which gave better control over the size etc.

Shouldn't be too hard to ensure that the plug-ins are 'installed' when creating the new instance, but 'activating' them in WP might be harder, unless we're in the game of just copying the database wholesale rather then re-building it from, say, an XML file - Unless the plug-in activation settings are captured in the XML that is
