### ISSUE TITLE
Evaluate DesFIRE cards

### ISSUE THREAD

**Issue by BarnabyShearer** [reading-hackspace/Infrastructure#12]
The Mifare cards we use are fairly broken. DesFIRE EV1 are now redly available at reasonable ~£1 prices.

Encryption and non-duplicable card-ids still thought to be fully secure.
Multiple keys and Applications on the same card. Vending machine can securely track credit without effecting door security etc.
Works with most phones (read, write, auth etc.)
For SurSAR I have code working with the same hardware as in the door.
We can transition supporting both cards.

**Comment by robot-army** [comment]
Do I need to buy some cards? I just bought a bunch of mifare cards not too long ago :(

**Comment by BarnabyShearer** [comment]
We have enough for testing/development. I think the are lower hanging security fruit on the physical side. Really comes down to the open question if the extra functionality is worth it. Would the vending machine guys really like it?
Someone mentioned room tablets; are they NFC?

**Comment by Gavatastic** [comment]
No- the tablets don't have NFC (they're Tegra Note 7)

**Comment by jeremypoulter** [comment]
For the vending machine (at least the initial version) I was just going to
use the serial number as the payment was only going to be an honour box.
Maybe if we then move to automatic electronic payments and actually
physically secure the vending machine then I may want to worry a bit more
about improved security.
