### ISSUE TITLE
Password Vault

### ISSUE THREAD

**Issue by jeremypoulter** [reading-hackspace/Infrastructure#14]
We could do with a Password Vault to store account details for systems that only have a single username/passwords

At a min this is needed for Twitter and EmonCMS.

**Comment by BarnabyShearer** [comment]
This may raise the issue of email for password resets and the like.
Day do day we could use TweedDeck teams to manage the account without sharing passswords.

**Comment by BarnabyShearer** [comment]
For clarity, I do agree we need a vault.
Personally I just use plain GPG encrypted text files in Git, and Ansible's vaults
