### ISSUE TITLE
Take ownership of Google Calendar

### ISSUE THREAD

**Issue by jeremypoulter** [reading-hackspace/Infrastructure#16]
I believe Mike The Bee has this

**Comment by JamesBelchamber** [comment]
Mike thinks his calendar has been replaced by Stuart's calendar. We should follow up with Stuart about this.

**Comment by JamesBelchamber** [comment]
We might have a Google Apps domain we can use for this purpose.

**Comment by xplora1a** [comment]
I have this at the Calendar:
googleapi://stuart.ward.uk@gmail.com/?calendar=e5dcr4pner511mglurj6oui4ao%40group.calendar.google.com
