### ISSUE TITLE
Take ownership of IFTTT rules for Facebook

### ISSUE THREAD

**Issue by jeremypoulter** [reading-hackspace/Infrastructure#21]
Currently I have two rules for auto posting new blog and podcast entries to the Facebook page. These are currently running from my personal IFTTT account, but we should create an rLab account and move them over.

Depends on #14 as IFTTT is a single user login.

We could also consider other web automation things, Ansible?

**Comment by JamesBelchamber** [comment]
Could you post the IFTTT flows?

**Comment by jeremypoulter** [comment]
Not to sure there is an easy way to do this but essentially they are;
- If new feed item from http://rlab.org.uk/feed/, then upload a photo from URL on Reading Hackspace Facebook page
- If new feed item from http://podcast.rlab.org.uk/?feed=rss2, then create a link post on Reading Hackspace Facebook page

**Comment by jeremypoulter** [comment]
We can probably do something similar to this for Twitter but need to check with @Gavatastic

**Comment by Gavatastic** [comment]
^ Would this be automatic? I have reservations about automatically pushing content out across platforms as I think it can pay to differentiate content by platform. For instance I currently see Twitter as being about raising profile and drawing people in, the website for giving the longer read/pitching the benefits of joining. There's some overlap and cross-referencing but I think best to curate.

**Comment by jeremypoulter** [comment]
So for Facebook I automatically post about new articles on the rLab
website, and now podcasts. The I will manually post anything else I think
should be up there. I also have a rule to notify me explicitly about
twitter posts which I will manually post (often reformatting) to Facebook.

IFTTT allows you to specify exactly what is posted in terms of text,
images, URLs etc so it can be designed to fit in with the target medium.

**Comment by jeremypoulter** [comment]
Neither of these sources exist any more
