### ISSUE TITLE
Discovery of current rLab email and calendaring setup

### ISSUE THREAD

**Issue by JamesBelchamber** [reading-hackspace/Infrastructure#22]

**Comment by JamesBelchamber** [comment]
TVRRUG and rLab google calendar exist and are looked after by Stuart and Mike respectively, but there are also others.

**Comment by xplora1a** [comment]
tvrrug calendar is https://calendar.google.com/calendar/embed?src=ckbu4p4srnihd3fbs8r5nvr70k%40group.calendar.google.com&ctz=Europe/London
