### ISSUE TITLE
Take ownership of the Signup Form

### ISSUE THREAD

**Issue by JamesBelchamber** [reading-hackspace/Infrastructure#3]
This will track the process of the IWG taking ownership of the rLab Signup Form. It is expected that discussion will happen and stories will be created before this can be accepted as done. Details:
- Signup form
  - Python CGI
  - Doesn't store data
  - Sends encrypted email

**Comment by BarnabyShearer** [comment]
https://github.com/reading-hackspace/signup_form

Needs gpg setup with the relevant keys, and a SSH key with very locked down access to the door for retrieving the list of pending tokens.

Note this code is the very epitome of the 'hack' philosophy.
