### ISSUE TITLE
Take ownership of the DNS configuration

### ISSUE THREAD

**Issue by JamesBelchamber** [reading-hackspace/Infrastructure#4]
- DNS Server
  - BIND
  - for rlab.org.uk

**Comment by BarnabyShearer** [comment]
Don't think anyone wants it to be BIND; just need the two NS and a way to update.
The current NS are only provided with the bitfoke VM.
We also have readinghackspace.org.uk readinghacksoace.org and readingmakerspace.co.uk

**Comment by jeremypoulter** [comment]
How about https://aws.amazon.com/route53/? Like all AWS has good web management and API. It will cost but should be < $3 a month ($0.50 per domain and <$1 the other charges).

**Comment by JamesBelchamber** [comment]
Yes, unless someone has a hankering for managing a BIND server I think we can use a service for this. Route53 is good but costs money, and DigitalOcean would do it for free (this is what I use). There are others.

We should then make sure we can manage it. All these services have APIs, so we can just list the zones in GitHub and have the process of updating them being a simple Merge Request. Ansible has a bunch of modules that can handle different cloud providers, including Digital Ocean and AWS, here:

http://docs.ansible.com/ansible/list_of_cloud_modules.html

**Comment by BarnabyShearer** [comment]
We have CNAME, MX, TXT, SRV records etc. so not sure the ansible module will suffice, but we don't change them enough for an API to be a hard requirement. I do find Route53 very good myself.

**Comment by JamesBelchamber** [comment]
The Route53 Ansible module does handle all record types - frustratingly, the DO one doesn't.

I would like to see us provide a way to document the records in git and then use that to provision the records, because that way we get free documentation and stop people from having to "find the guy with access to the Route53 panel", which is generally what we're trying to get away from. Ansible does that, again there are others.
