### ISSUE TITLE
Decommission the Bitfolk server

### ISSUE THREAD

**Issue by JamesBelchamber** [reading-hackspace/Infrastructure#5]
It's creaky, it's old, let's get it gone.

**Comment by BarnabyShearer** [comment]
- [ ] Wiki (DB, MTA)
- [ ] Blog (DB)
- [ ] Signup page (MTA, SSL)
- [ ] Authoritative DNS
- [x] Confirm Email to Wiki Post system is obsolete
- [x] Confirm Label system is obsolete (Cups, wiki extensions, url shorting etc. etc.)
- [x] Confirm Bugzilla bugs.rlab.org.uk system is obsolete
- [ ] Confirm Planet/Venus feed alligator is obsolete
- [x] Confirm OpenLDAP is obsolete

**Comment by BarnabyShearer** [comment]
@robot-army ^ Email to wiki post, and Label are really for you.

**Comment by BarnabyShearer** [comment]
@daubers What are your thoughts on bugzilla

**Comment by daubers** [comment]
Bugzilla is junk, it never got used. Do what you want with it. There is however nothing wrong with the bitfolk server. It handles the wiki fine. Please do not change things which are not broken just for the sake of changing them! That way both madness and more broken-ness lies.

**Comment by BarnabyShearer** [comment]
It can't `apt-get update` becouse it hasn't been upgraded for so long; hundreds of high severity security updates pending. No documentation. No single person knows everything that is running on there. It is much easer to start fresh.

**Comment by robot-army** [comment]
bin the label and mail to wiki stuff
