### ISSUE TITLE
Document members, door entries and Xero subs data formats

### ISSUE THREAD

**Issue by Gavatastic** [reading-hackspace/Infrastructure#7]

**Comment by BarnabyShearer** [comment]
Currently the door system uses three files per token. These are numbered in a hex representation of the Mifare ID: 0x820x930xfd0xae.jpg, 0x820x930xfd0xae.txt, 0x8a0x8a0x390x15.dat

The JPEG is a mugshot of the member. The DAT file is the 1K memory dump of the card (containing all keys and verification data), and the txt file is 
REGEX for finding bank payments
Full Name
Email
Address

The DAT files are on the door itself; the other files are only send over PGP encrypted emails, and stored encrypted on my laptop.

**Comment by BarnabyShearer** [comment]
The code running the door which uses the DAT files is https://zi.is/p/browser/bridgeofdeath

**Comment by BarnabyShearer** [comment]
http://developer.xero.com/documentation/api/api-overview/

**Comment by BarnabyShearer** [comment]
I did also write a webservice for authenticating against the members list:

https://members.rlab.org.uk/static/doc/index.html
